In [1]:
import requests
import pandas as pd

In [2]:
url = "https://jsonplaceholder.typicode.com/posts"

response = requests.get(url)

print(response.status_code)

200

In [3]:
data = response.json()

print(type(data))
print(data[:3])

<class 'list'>
[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

In [4]:
df = pd.DataFrame(data)

df.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [5]:
print(df.shape)
print(df.columns)
print(df.dtypes)

(100, 4)
Index(['userId', 'id', 'title', 'body'], dtype='object')
userId     int64
id         int64
title     object
body      object
dtype: object

In [6]:
df.to_csv("api_data.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [7]:
pd.read_csv("api_data.csv").head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [8]:
import os

print(os.path.abspath("api_data.csv"))
print(os.path.exists("api_data.csv"))

C:\Users\sujat\api_data.csv
True

In [9]:
csv_df = pd.read_csv("api_data.csv")

print("Rows:", csv_df.shape[0])
print("Columns:", csv_df.shape[1])
print("Column names:", list(csv_df.columns))

Rows: 100
Columns: 4
Column names: ['userId', 'id', 'title', 'body']

In [10]:
from IPython.display import FileLink

FileLink("api_data.csv")

C:\Users\sujat\api_data.csv